### ISSUE TITLE
Syntax error on line 12

### ISSUE THREAD

**Issue by GalexY727** [valitydev/action-download-file#10]
Hi, and sorry in advance, but I am really new to GitHub Actions and was wondering why there was a syntax error in the example usage for your action. I was trying to download a file from [minimalistic-wallpaper.demolab.com](https://minimalistic-wallpaper.demolab.com/?random) but do not know how to implement your program. Any help is appreciated!
[Here is my exact actions output.](https://github.com/GalexY727/GalexY727/actions/runs/3646421611/workflow)

**Comment by tolkonepiu** [comment]
Hi, @GalexY727!

Yes, you're right. There was an extra indent in the example, which caused the error:

https://github.com/valitydev/action-download-file/pull/11/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R25-L26

Thank you!

**Comment by tolkonepiu** [comment]
Fix in #11
